### ISSUE TITLE
help making customisations

### ISSUE THREAD

**Issue by liam8888999** [Nessus85100/skin.bello.7#26]
could you please tell the files to edit to adjust the look of the videos page. in particular to move the images and writing to the other side of the screen. right side to left side.
![Screen Shot 2021-05-22 at 11 54 14 pm](https://user-images.githubusercontent.com/79149245/119228993-142e6380-bb59-11eb-8c4d-e2a890fa4607.png)

**Comment by Nessus85100** [comment]
- [IncludesViews.xml](https://github.com/Nessus85100/skin.bello.7/blob/master/720p/IncludesViews.xml)
From line [101](https://github.com/Nessus85100/skin.bello.7/blob/master/720p/IncludesViews.xml#L101) until line [556](https://github.com/Nessus85100/skin.bello.7/blob/master/720p/IncludesViews.xml#L556)

- [ViewsVideos.xml](https://github.com/Nessus85100/skin.bello.7/blob/master/720p/ViewsVideos.xml)
From line [7](https://github.com/Nessus85100/skin.bello.7/blob/master/720p/ViewsVideos.xml#L7) until line [275](https://github.com/Nessus85100/skin.bello.7/blob/master/720p/ViewsVideos.xml#L275)

Keep in mind that this is the basic view for all Kodi sections so check the adjusted positions if they are the proper ones for all of them.

Cheers
Nessus

**Comment by liam8888999** [comment]
what do you mean by the basic view for all Kodi sections?

**Comment by Nessus85100** [comment]
The ListView has the same list on the left and 4 different layouts on the right with the appropriate info for every section (movies, tvshows, music, addons etc). If you change the position of the list eg in movies it will change in all sections so you need also to adjust the positions of the rest of the 4 layouts.

Also keep in mind that in a couple of weeks i will release Bello 8. So you will need to do the same changes again if you want to update.

Cheers
Nessus

**Comment by fingoltin** [comment]
How did you change the highlight colour for the selected item?

**Comment by Nessus85100** [comment]
The developing of Bello 7 has stopped. [Bello 8](https://github.com/Nessus85100/skin.bello.8) is out now and available through Kodi official repo.

In the future please post any issues there.

Since your question is valid also for Bello 8, you can change the basic colors of the skin via the [colors.xml](https://github.com/Nessus85100/skin.bello.8/blob/master/colors/defaults.xml) file or you can change the color of all highlighted text in skin settings.

Cheers
Nessus
